# Generated by Django 3.2.8 on 2022-01-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationDetails',
            fields=[
                ('reg_id', models.IntegerField(db_column='Reg_id', primary_key=True, serialize=False)),
                ('vaccine_count', models.IntegerField()),
                ('booking_status', models.SmallIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
